### ISSUE TITLE
Make it possible to use typist in multiple View controllers at the same time

### ISSUE THREAD

**Issue by mman** [totocaster/Typist#11]
I'm aware of the current limitations of using a singleton instance and start/stop methods to setup and remove listeners. 

I'm opening this issue to start conversation about how to best address this limitation so that multiple typist instances can be setup at the same time for example from a full screen view controller on the iPad and another modally present page view controller that is occupying just part of the screen (page modal view controller)

Quickly thinking out loud I think it should be possible instead of using a singleton just instantiate and start typist in viewDidLoad and stop it in deinit...

Any thoughts on this?

Thanks
Martin

**Comment by totocaster** [comment]
Thanks for starting this thread. 

Few days ago, I modified README by adding few notes regarding singleton usage. Singleton is there only for shorthand purposes and situation when only one Typist instance is enough.

However, using concrete instance of Typist is highly encouraged. Doing so eliminates all limitations of singleton pattern. 

I'm happy to modify and reword README yet again to make this clear.

**Comment by mman** [comment]
I understand now, so it's in fact possible to actually already use multiple instances at the same time, it was just not clear to me from the README... I'll try to create another PR with suggested README examples...

thanks,

**Comment by mman** [comment]
I'm just thinking, what do you consider to be the best practice on when and how to setup Typist.
1. When to call `.on(event)` ?
2. When to call `.start()` ?
3. Is it ever necessary to call  `.stop()` at all ?

My assumption was to call `.on(event)` and `.start()` from `viewDidLoad` and `.stop()` and `.clear()` from `deinit` but looking at the code again I think it might not be necessary at all to call `.stop()` or `.clear().` Will this lead to retain cycles due to `NSDefaultNotificationCenter` keeping reference on our class? Will this prevent my view controllers from being deallocated properly?

This is probably something that I'd like to get clarified in the README, to outline the best practice when using Typist in one, or more view controllers at the same time...

**Comment by totocaster** [comment]
`viewDidLoad()`, `viewWillAppear()` or any configuration method you choose is a good place to instantiate and configure Typist. As for `start()` — it really depends on what you app does, in most cases probably right after configuration, but again, it depends an how do you control flow of you app.

Calling `stop()` is good idea just not to ask OS deliver keyboard notification that are not necessary. 

`clear()` is convince method made for cases when you need to redefine/reconfigure same typist instance. You don't need it if you are not planing to reconfigure your instance.

> Will this lead to retain cycles due to NSDefaultNotificationCenter keeping reference on our class? Will this prevent my view controllers from being deallocated properly?

I'm not sure I understand this, notification center doesn't not have any strong coupling with object it is sending messages to.
