### ISSUE TITLE
How to use options.animationCurve?

### ISSUE THREAD

**Issue by kgn** [totocaster/Typist#12]
I'm trying to setup a `UIView` animation to match the keyboard animation, including the animation curve. `.animationCurve` is available from `Typist.KeyboardOptions`, but I'm getting a type error. Any way around this?

``` swift
UIView.animate(withDuration: options.animationDuration, delay: 0, options: options.animationCurve, animations: {
    self.view.layoutIfNeeded()
}, completion: nil)
```

```
Cannot convert value of type 'UIViewAnimationCurve' to expected argument type 'UIViewAnimationOptions'
```

**Comment by nezhyborets** [comment]
I used this which seems right to me https://gist.github.com/miguellara/9e498715ee93540d79e9. I would suggest that it should be included to Typist

**Comment by kgn** [comment]
@nezhyborets does this work for multiple values like `[.beginFromCurrentState, .curveEaseInOut]`?

**Comment by nezhyborets** [comment]
It is simply a converter from single value of type `UIViewAnimationCurve` to single value of type `UIViewAnimationOptions`. You could do, for example:
```swift
let animationCurve = UIViewAnimationCurve.easeInOut
let animationOption = viewAnimationOptionForCurve(curve: animationCurve)
let options = [.beginFromCurrentState, option]
```

**Comment by kgn** [comment]
Updated for Swift3

``` swift
func animationOptions(fromAnimationCurve curve: UIViewAnimationCurve) -> UIViewAnimationOptions {
    switch (curve) {
        case .easeInOut: return UIViewAnimationOptions.curveEaseInOut
        case .easeIn: return UIViewAnimationOptions.curveEaseIn
        case .easeOut: return UIViewAnimationOptions.curveEaseOut
        case .linear: return UIViewAnimationOptions.curveLinear
    }
}
```

**Comment by totocaster** [comment]
Hey, thanks for opening issue! Typist is designed to be used with `UIViewPropertyAnimator` (see below) rather older `UIView` animation blocks. 

```
UIViewPropertyAnimator(duration: TimeInterval, curve: UIViewAnimationCurve, animations: (() -> Void)? = nil)
```

However, I'll consider adding few other representations for curves for pre-iOS 10 compatibility reasons.

**Comment by kgn** [comment]
@totocaster I switched to this code

``` swift
func keyboardWillShow(options: Typist.KeyboardOptions) {
    self.loginButtonConstraint.constant = -options.endFrame.height-Style.Size.Padding
    UIViewPropertyAnimator(duration: options.animationDuration, curve: options.animationCurve) {
        self.view.layoutIfNeeded()
    }.startAnimation()
}
```

but now getting this error

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unknown/Unsupported UIViewAnimationCurve type 7'
```

**Comment by totocaster** [comment]
@kgn I believe you have to keep reference to instance of `UIViewPropertyAnimator` while animation happens. If you don't wish to do so use `UIViewPropertyAnimator .runningPropertyAnimator(withDuration:delay:options:animations:completion:)`. It also start animation automatically.

See [UIViewPropertyAnimator docs here](https://developer.apple.com/reference/uikit/uiviewpropertyanimator).
