### ISSUE TITLE
Add toolbar support

### ISSUE THREAD

**Issue by efremidze** [totocaster/Typist#15]
Add toolbar support similar to [RxKeyboard](https://github.com/RxSwiftCommunity/RxKeyboard) with interactive panning support. I can make a PR.

**Comment by totocaster** [comment]
That's a great idea! We can discuss API design here before submitting PR/implementation in case you have not done it yet.

**Comment by totocaster** [comment]
⚠️ Development is on `feature/interactive`. Keeping this issue open till merge to master.
