### ISSUE TITLE
Swift 4.2 Release

### ISSUE THREAD

**Issue by anthonycastelli** [totocaster/Typist#24]
Can we get a tagged Swift 4.2 release for this?

**Comment by colinhumber** [comment]
👍

**Comment by totocaster** [comment]
Tagged as 1.3, will push cocoapods soon as well. Thanks!

**Comment by colinhumber** [comment]
The Swift version referenced in `.swift-version` is still 4.0 which will set the wrong Swift version in the build settings when installing the pod, causing compile errors. I've made a PR to remove this deprecated file and set the Swift version in the podspec, as is the now recommended approach.

https://github.com/totocaster/Typist/pull/27

This should be included, or at least the version in `.swift-version` updated and this retagged as 1.3 before pushing to the main spec repo.
