### ISSUE TITLE
ios 12 changes 

### ISSUE THREAD

**Issue by sowri** [totocaster/Typist#26]
Seems like lot of constants have changed,
'UIApplicationDidBecomeActive' has been renamed to 'UIApplication.didBecomeActiveNotification'
'kCAFillModeBoth' has been renamed to 'CAMediaTimingFillMode.both'
'UIApplicationDidBecomeActive' has been renamed to 'UIApplication.didBecomeActiveNotification'

and a few more

**Comment by Tylerian** [comment]
Those are Swift 4.2 changes rather than iOS 12, but yeah, the codebase should be updated.

**Comment by Tylerian** [comment]
I think those Swift 4.2 changes are already pushed against master but @totocaster didn't flag a release for them.

**Comment by totocaster** [comment]
Tagged as 1.3, will be pushing to cocoapods soon. Thanks!
