### ISSUE TITLE
Please fix SMP support

### ISSUE THREAD

**Issue by nikans** [totocaster/Typist#35]
<img width="514" alt="Screenshot 2020-06-19 at 22 49 17" src="https://user-images.githubusercontent.com/1039100/85174964-220ba280-b27f-11ea-915e-ec1074930d0b.png">

same for latest 1.4.2

**Comment by totocaster** [comment]
Hi @nikans, I've made #36. Please feel free to contribute. Will merge if all looks ok.

**Comment by nikans** [comment]
Thanks )
