### ISSUE TITLE
SPM Doesn't work, please add 1.4.3 release

### ISSUE THREAD

**Issue by timdolenko** [totocaster/Typist#37]
Same issue as #35, the problem is that SPM reads Github releases and cannot find 1.4.3.

Just add 1.4.3 release to fix it. 

<img width="748" alt="Screenshot 2021-05-14 at 11 38 48" src="https://user-images.githubusercontent.com/35912614/118252521-251c0c80-b4a9-11eb-8c80-167438e2f70e.png">

It works here: https://github.com/tymofiidolenko/Typist/releases/tag/1.4.3

I have XCode 12.5

**Comment by timdolenko** [comment]
@totocaster should be easy to fix

**Comment by enrico-querci** [comment]
ping 💚

**Comment by totocaster** [comment]
Should be working now, thanks for the ping. 👍

**Comment by enrico-querci** [comment]
Thanks, it works like a charm on Xcode 12.5 👍 Feel free to close the issue!
